#!/bin/bash
#$ -pe openmpi 8
#$ -l h_rt=0:15:00
#$ -N out.c1
#$ -cwd

MPI=/var/scratch/jason/OpenMPI/openmpi-1.4.2-fixed-gnu

APP=./app.exe
ARGS="--wa-server fs0.das4.cs.vu.nl --wa-server-port 45678 --wa-cluster-name VU4.C1 --wa-cluster-rank 0 --wa-cluster-count 2"

# Get OpenMPI settings
. /etc/bashrc

# Make new hostfile specifying the cores per node wanted
ncores=8
HOSTFILE=$TMPDIR/hosts
for host in `uniq $TMPDIR/machines`; do
    echo $host slots=$ncores
done > $HOSTFILE
nhosts=`wc -l < $HOSTFILE`
totcores=`expr $nhosts \* $ncores`

# Use regular ssh-based startup instead of OpenMPI/SGE native one
unset PE_HOSTFILE
PATH=/usr/bin:$PATH

$MPI/bin/mpirun -np $totcores --hostfile $HOSTFILE -output-filename out.c1 $APP $ARGS

