#!/bin/bash
#$ -pe openmpi 64
#$ -l h_rt=0:15:00
#$ -N testapp
#$ -cwd

APP=./app.exe
ARGS="--wa-server fs0.das4.cs.vu.nl --wa-server-port 45678 --wa-cluster-name VU4 --wa-cluster-rank 0 --wa-cluster-count 1"

# Get OpenMPI settings
. /etc/bashrc
#module load intel/compiler/64/11.1/075
#module load openmpi

# Make new hostfile specifying the cores per node wanted
ncores=8
HOSTFILE=$TMPDIR/hosts
for host in `uniq $TMPDIR/machines`; do
    echo $host slots=$ncores
done > $HOSTFILE
nhosts=`wc -l < $HOSTFILE`
totcores=`expr $nhosts \* $ncores`

# Use regular ssh-based startup instead of OpenMPI/SGE native one
unset PE_HOSTFILE
PATH=/usr/bin:$PATH

setenv LD_LIBRARY_PATH /cm/shared/apps/intel/composer_xe/current/compiler/lib/intel64

/var/scratch/jason/OpenMPI/openmpi-1.4.2-fixed-gnu/bin/mpirun -np $totcores --hostfile $HOSTFILE -output-filename out $APP $ARGS

